{% set name = "delve" %}
{% set version = "1.23.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/go-delve/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 52554d682e7df2154affaa6c1a4e74ead1fe53959ac630f1118317031160a47d

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - dlv --help

about:
  home: https://github.com/go-delve/{{ name }}
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Debugger for the Go programming language
  dev_url: https://github.com/go-delve/{{ name }}

extra:
  recipe-maintainers:
    - danielnachun
