{% set name = "delve" %}
{% set version = "1.23.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/go-delve/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: fed613f0457600a30713968c111bb1fc3b014a4ebb25acaaf45cdbd03f8337a1

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - dlv --help

about:
  home: https://github.com/go-delve/{{ name }}
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Debugger for the Go programming language
  dev_url: https://github.com/go-delve/{{ name }}

extra:
  recipe-maintainers:
    - danielnachun
