schema_version: 1

context:
  version: "1.26.3"

package:
  name: delve
  version: ${{ version }}

source:
  url: https://github.com/go-delve/delve/archive/v${{ version }}.tar.gz
  sha256: c5abd02033d7601a41bb6748589c0be42080dc4f91c7e48fc8cbb7f558cc8748

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - dlv --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Debugger for the Go programming language
  homepage: https://github.com/go-delve/delve
  repository: https://github.com/go-delve/delve

extra:
  recipe-maintainers:
    - danielnachun
