schema_version: 1

context:
  version: "1.27.1"

package:
  name: delve
  version: ${{ version }}

source:
  url: https://github.com/go-delve/delve/archive/v${{ version }}.tar.gz
  sha256: dca9ec6f2c392a00449ad748b3a229e92ba4efa67f4e7582f2cc45974429928f

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - dlv --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Debugger for the Go programming language
  homepage: https://github.com/go-delve/delve
  repository: https://github.com/go-delve/delve

extra:
  recipe-maintainers:
    - danielnachun
