schema_version: 1

context:
  version: "1.26.2"

package:
  name: delve
  version: ${{ version }}

source:
  url: https://github.com/go-delve/delve/archive/v${{ version }}.tar.gz
  sha256: b3be68f1207076e539268f0c502a7d399e798c18f6998860dbf0bdf80eb77f44

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - dlv --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Debugger for the Go programming language
  homepage: https://github.com/go-delve/delve
  repository: https://github.com/go-delve/delve

extra:
  recipe-maintainers:
    - danielnachun
